# Generated by Django 2.2 on 2019-04-09 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20190409_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='startDate',
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
