# Generated by Django 2.2 on 2019-04-23 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_auto_20190415_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
