# Generated by Django 2.2 on 2019-04-23 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_auto_20190423_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
